CATEGORIES = {
    "Forex Major": [
        "EURUSDm", "GBPUSDm", "USDJPYm", "USDCHFm",
        "USDCADm", "AUDUSDm", "NZDUSDm",
    ],
    "Forex Cross": [
        "EURAUDm", "EURCADm", "EURCHFm", "EURGBPm", "EURJPYm", "EURNZDm",
        "GBPAUDm", "GBPCADm", "GBPCHFm", "GBPJPYm", "GBPNZDm",
        "AUDCADm", "AUDCHFm", "AUDJPYm", "AUDNZDm",
        "CADCHFm", "CADJPYm", "CHFJPYm",
        "NZDCADm", "NZDCHFm", "NZDJPYm",
    ],
    "Forex Exotic": [
        "AUDCZKm", "AUDDKKm", "AUDHUFm", "AUDMXNm", "AUDNOKm",
        "AUDPLNm", "AUDSEKm", "AUDSGDm", "AUDTRYm", "AUDZARm",
        "CADCZKm", "CADMXNm", "CADNOKm", "CADPLNm", "CADTRYm",
        "CHFDKKm", "CHFHUFm", "CHFMXNm", "CHFNOKm", "CHFPLNm",
        "CHFSEKm", "CHFSGDm", "CHFTRYm", "CHFZARm",
        "CZKPLNm", "DKKCZKm", "DKKHUFm", "DKKJPYm", "DKKPLNm",
        "DKKSGDm", "DKKZARm",
        "EURCZKm", "EURDKKm", "EURHKDm", "EURHUFm", "EURMXNm",
        "EURNOKm", "EURPLNm", "EURSEKm", "EURSGDm", "EURTRYm", "EURZARm",
        "GBPCZKm", "GBPDKKm", "GBPHUFm", "GBPILSm", "GBPMXNm",
        "GBPNOKm", "GBPPLNm", "GBPSEKm", "GBPSGDm", "GBPTRYm", "GBPZARm",
        "HKDJPYm", "HUFJPYm", "MXNJPYm",
        "NOKDKKm", "NOKJPYm", "NOKSEKm",
        "NZDCZKm", "NZDDKKm", "NZDHUFm", "NZDMXNm", "NZDNOKm",
        "NZDPLNm", "NZDSEKm", "NZDSGDm", "NZDTRYm", "NZDZARm",
        "PLNDKKm", "PLNHUFm", "PLNJPYm", "PLNSEKm",
        "SEKDKKm", "SEKJPYm", "SEKPLNm",
        "SGDHKDm", "SGDJPYm",
        "TRYDKKm", "TRYJPYm", "TRYZARm",
        "USDAEDm", "USDAMDm", "USDAOAm", "USDARSm", "USDAZNm",
        "USDBDTm", "USDBGNm", "USDBHDm", "USDBNDm", "USDBRLm",
        "USDCLPm", "USDCNHm", "USDCNYm", "USDCOPm", "USDCZKm",
        "USDDKKm", "USDDZDm", "USDEGPm", "USDGELm", "USDGHSm",
        "USDGTQm", "USDHKDm", "USDHNLm", "USDHRKm", "USDHUFm",
        "USDIDRm", "USDILSm", "USDINRm", "USDIQDm", "USDISKm",
        "USDJODm", "USDKESm", "USDKGSm", "USDKRWm", "USDKWDm",
        "USDKZTm", "USDLBPm", "USDLKRm", "USDMADm", "USDMXNm",
        "USDMYRm", "USDNGNm", "USDNOKm", "USDNPRm", "USDOMRm",
        "USDPHPm", "USDPKRm", "USDPLNm", "USDQARm", "USDRONm",
        "USDRUBm", "USDRURm", "USDSARm", "USDSEKm", "USDSGDm",
        "USDSYPm", "USDTHBm", "USDTJSm", "USDTMTm", "USDTNDm",
        "USDTRYm", "USDTWDm", "USDUAHm", "USDUGXm", "USDUZSm",
        "USDVNDm", "USDVUVm", "USDXOFm", "USDZARm",
        "ZARJPYm",
    ],
    "Crypto": [
        "1INCHUSDm", "AAVEUSDm", "ADAUSDm", "BATUSDm", "BCHUSDm",
        "BNBUSDm", "BTCAUDm", "BTCCNHm", "BTCJPYm", "BTCKRWm",
        "BTCTHBm", "BTCUSDTm", "BTCUSDm", "BTCXAGm", "BTCXAUm",
        "BTCZARm", "CAKEUSDm", "COMPUSDm", "DOGEUSDm", "DOTUSDm",
        "ENJUSDm", "ETHBTCm", "ETHUSDm", "FILUSDm", "HBARUSDm",
        "IOSTUSDm", "LINKUSDm", "LTCUSDm", "MANAUSDm", "MATICUSDm",
        "SNXUSDm", "SOLUSDm", "THETAUSDm", "UNIUSDm", "XRPUSDm",
        "XTZUSDm",
    ],
    "Indices": [
        "AUS200m", "DE30m", "DXYm", "FR40m", "HK50m",
        "IN50m", "JP225m", "STOXX50m", "UK100m",
        "US30m", "US500m", "USTECm",
        "US30_x10m", "US500_x100m", "USTEC_x100m",
    ],
    "Metals": [
        "XAUUSDm", "XAGUSDm", "XAUEURm", "XAUGBPm", "XAUAUDm",
        "XAGEURm", "XAGGBPm", "XAGJPYm", "XAGAUDm",
    ],
    "Commodities": [
        "UKOILm", "USOILm", "XCUUSDm", "XNGUSDm", "XALUSDm",
        "XPDUSDm", "XPTUSDm", "XNIUSDm", "XZNUSDm",
    ],
    "Stocks": [
        "AAPLm", "ABBVm", "ABTm", "ADBEm", "ADPm", "AMCm", "AMDm",
        "AMGNm", "AMTm", "AMZNm", "ATVIm", "AVGOm", "BABAm", "BACm",
        "BAm", "BBBYm", "BBm", "BEKEm", "BIDUm", "BIIBm", "BILIm",
        "BMYm", "BRQSm", "BYNDm", "CANm", "CHTRm", "CMCSAm", "CMEm",
        "COSTm", "CSCOm", "CSXm", "CVSm", "Cm", "EAm", "EBAYm",
        "EDUm", "EQIXm", "FBm", "FTNTm", "FUTUm", "Fm", "GILDm",
        "GOOGLm", "HDm", "IBMm", "INTCm", "INTUm", "IQm", "ISRGm",
        "JDm", "JNJm", "JPMm", "KOm", "LINm", "LIm", "LLYm",
        "LMTm", "MAm", "MCDm", "MDLZm", "METAm", "MMMm", "MOm",
        "MRKm", "MSFTm", "MSm", "NFLXm", "NIOm", "NKEm", "NTESm",
        "NVDAm", "ORCLm", "PDDm", "PEPm", "PFEm", "PGm", "PMm",
        "PYPLm", "REGNm", "RLXm", "SBUXm", "SPCXm", "TALm",
        "TIGRm", "TMEm", "TMOm", "TMUSm", "TSLAm", "TSMm", "Tm",
        "UNHm", "UPSm", "VIPSm", "VRTXm", "VZm", "Vm", "WFCm",
        "WMTm", "XOMm", "XPEVm", "YUMCm", "ZTOm",
    ],
}
